data = {
  portfolios: [
    {
      title: "Job in Netcentric",
      company: "Netcentric",
      companyWebsite: "www.google.com",
      location: "Spain, Barcelona",
      jobTitle: "Engineer",
      description: "Doing something, programing....",
      userId: "google-oauth2|105332304620487549617",
      startDate: "01/01/2014",
      endDate: "01/01/2016",
    },
    {
      title: "Job in Siemens",
      company: "Siemens",
      companyWebsite: "www.google.com",
      location: "Slovakia, Kosice",
      jobTitle: "Software Engineer",
      description: "Responsoble for parsing framework for JSON medical data.",
      userId: "google-oauth2|105332304620487549617",
      startDate: "01/01/2011",
      endDate: "01/01/2013",
    },
    {
      title: "Work in USA",
      company: "WhoKnows",
      companyWebsite: "www.google.com",
      location: "USA, Montana",
      jobTitle: "Housekeeping",
      description: "So much responsibility....Overloaaaaaad",
      userId: "google-oauth2|105332304620487549617",
      startDate: "01/01/2010",
      endDate: "01/01/2011",
    },
    {
      title: "Work in Alaska",
      company: "AlaskaTtraveler",
      companyWebsite: "www.AlaskaTtraveller.com",
      location: "USA, Alaska",
      jobTitle: "Ttraveler free man ",
      description:
        "travel over the world as much as possible and continue safely",
      userId: "google-oauth2|105332304620487549617",
      startDate: "01/01/2024",
      endDate: "01/01/2027",
    },
    {
      title: "Work in Tesla",
      company: "Tesla",
      companyWebsite: "www.tesla.com",
      location: "USA, california",
      jobTitle: "Electronic Engineer",
      description: "happy to work as engineer in this company",
      userId: "google-oauth2|105332304620487549617",
      startDate: "01/01/2023",
      endDate: "01/01/2030",
    },
  ],

  blogs: [
    {
      slug: "my-first-blog",
      title: "My First Blog",
      subTitle: "It was chilly winter day...",
      content: "<p>Some very nice content</p>",
      userId: "google-oauth2|105332304620487549617",
      status: "published",
    },
    {
      slug: "my-second-blog",
      title: "My Second Blog",
      subTitle: "It was hot summer day...",
      content: "<p>Some very nice content</p>",
      userId: "google-oauth2|105332304620487549617",
      status: "published",
    },
    {
      slug: "my-third-blog",
      title: "My Third Blog",
      subTitle: "It was rainy spring day...",
      content: "<p>Some very nice content</p>",
      userId: "google-oauth2|105332304620487549617",
      status: "published",
    },
  ],
};

module.exports = data;
